// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.BoardConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BoardConfigurations");
                });

            modelBuilder.Entity("api.Models.Climb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BoardConfigurationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("CustomLocationLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("CustomLocationLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("CustomLocationName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Discipline")
                        .HasColumnType("integer");

                    b.Property<string>("FirstAscentName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("GradeSystem")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("integer");

                    b.Property<int?>("SetterId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BoardConfigurationId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("SetterId");

                    b.ToTable("Climbs", t =>
                        {
                            t.HasCheckConstraint("CK_Climbs_Context", "\r\n(\r\n    \"PlaceId\" IS NOT NULL\r\n    AND \"BoardConfigurationId\" IS NULL\r\n    AND \"CustomLocationName\" IS NULL\r\n    AND \"CustomLocationLatitude\" IS NULL\r\n    AND \"CustomLocationLongitude\" IS NULL\r\n)\r\nOR (\r\n    \"PlaceId\" IS NULL\r\n    AND \"BoardConfigurationId\" IS NOT NULL\r\n    AND \"CustomLocationName\" IS NULL\r\n    AND \"CustomLocationLatitude\" IS NULL\r\n    AND \"CustomLocationLongitude\" IS NULL\r\n)\r\nOR (\r\n    \"PlaceId\" IS NULL\r\n    AND \"BoardConfigurationId\" IS NULL\r\n    AND \"CustomLocationName\" IS NOT NULL\r\n    AND \"CustomLocationLatitude\" IS NOT NULL\r\n    AND \"CustomLocationLongitude\" IS NOT NULL\r\n)");
                        });
                });

            modelBuilder.Entity("api.Models.ClimbExternalReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClimbId")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClimbId");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("ClimbExternalReferences");
                });

            modelBuilder.Entity("api.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ClimbId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClimbId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("api.Models.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClimbId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("integer");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClimbId");

                    b.HasIndex("PlaceId");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("api.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParentPlaceId")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentPlaceId");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("api.Models.PlaceExternalReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("PlaceExternalReferences");
                });

            modelBuilder.Entity("api.Models.Setter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Setters");
                });

            modelBuilder.Entity("api.Models.Climb", b =>
                {
                    b.HasOne("api.Models.BoardConfiguration", "BoardConfiguration")
                        .WithMany("Climbs")
                        .HasForeignKey("BoardConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("api.Models.Place", "Place")
                        .WithMany("Climbs")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("api.Models.Setter", "Setter")
                        .WithMany("Climbs")
                        .HasForeignKey("SetterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BoardConfiguration");

                    b.Navigation("Place");

                    b.Navigation("Setter");
                });

            modelBuilder.Entity("api.Models.ClimbExternalReference", b =>
                {
                    b.HasOne("api.Models.Climb", "Climb")
                        .WithMany("ExternalReferences")
                        .HasForeignKey("ClimbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Climb");
                });

            modelBuilder.Entity("api.Models.Comment", b =>
                {
                    b.HasOne("api.Models.Climb", "Climb")
                        .WithMany("Comments")
                        .HasForeignKey("ClimbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Climb");
                });

            modelBuilder.Entity("api.Models.LogEntry", b =>
                {
                    b.HasOne("api.Models.Climb", "Climb")
                        .WithMany("LogEntries")
                        .HasForeignKey("ClimbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Place", "Place")
                        .WithMany("LogEntries")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Climb");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("api.Models.Place", b =>
                {
                    b.HasOne("api.Models.Place", "ParentPlace")
                        .WithMany("Children")
                        .HasForeignKey("ParentPlaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentPlace");
                });

            modelBuilder.Entity("api.Models.PlaceExternalReference", b =>
                {
                    b.HasOne("api.Models.Place", "Place")
                        .WithMany("ExternalReferences")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("api.Models.BoardConfiguration", b =>
                {
                    b.Navigation("Climbs");
                });

            modelBuilder.Entity("api.Models.Climb", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ExternalReferences");

                    b.Navigation("LogEntries");
                });

            modelBuilder.Entity("api.Models.Place", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Climbs");

                    b.Navigation("ExternalReferences");

                    b.Navigation("LogEntries");
                });

            modelBuilder.Entity("api.Models.Setter", b =>
                {
                    b.Navigation("Climbs");
                });
#pragma warning restore 612, 618
        }
    }
}
